name: collect

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: "15 4 * * 0"

jobs:
  run:
    name: |
      execute-action - ${{ github.event_name == 'schedule' && 'Scheduled Run' || 'Issue Comment' }}
    if: |
      github.event_name == 'schedule' || 
      (github.event_name == 'issue_comment') && contains(github.event.comment.body, '/collect')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.25"
      - name: Prepare go
        run: |
          go version
          go mod download
      - name: summary
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          OPENAI_BASE_URL: ${{ vars.OPENAI_BASE_URL }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OSS_ACCESS_KEY_ID: ${{ vars.ALIYUN_OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}
        run: |
          go run main.go
      - name: Prepare commit changes
        id: prepare_changes
        run: |
          git config --global user.email "${{ vars.EMAIL }}"
          git config --global user.name "${{ vars.NAME }}"
          git remote -v
          echo "branch=feat-$(date -u '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        env:
          BRANCH_NAME: ${{ steps.prepare_changes.outputs.branch }}
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          title: "feat: ${{ env.BRANCH_NAME }} blog posts"
          body: "Update ${{ env.BRANCH_NAME }} blog posts"
          commit-message: "update: ${{ env.BRANCH_NAME }} blog posts"
